services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  UI\UiPermissions\:
    resource: '../Classes/*'

  UI\UiPermissions\Command\PermissionUpdatesCommand:
    tags:
      - name: 'console.command'
        command: 'ui_permissions:update'
        description: 'Updates the configured permission definitions in the database'

  UI\UiPermissions\Configuration\ConfigurationCollector:
    public: true

  UI\UiPermissions\Domain\Repository\BackendUserGroupRepository:
    public: true

  UI\UiPermissions\Domain\Repository\FileMountRepository:
    public: true
